apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-api
  namespace: news-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: news-api
  template:
    metadata:
      labels:
        app: news-api
    spec:
      containers:
        - name: news-api
          image: ECR_REPO_URL:latest   # reemplazar con la URL del repo ECR
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
